name: 🐞 Bug Report
description: Create a report to help us improve
labels: ["type:Bug", "status:Unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: summary
    attributes:
      label: Issue Summary
      description: A summary of the issue.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue.
      value: |
        1. Start a new project with `wagtail start myproject`
        2. Edit models.py as follows...
        3. ...
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
    validations:
      required: false

  - type: dropdown
    id: reproducibility
    attributes:
      label: Can be reproduced
      description: Have you confirmed this issue on a fresh Wagtail project or the bakerydemo?
      options:
        - Not yet
        - Yes, on a fresh Wagtail project
        - Yes, on the bakerydemo

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: Run `python --version`
      placeholder: e.g., Python 3.11.5
    validations:
      required: true

  - type: input
    id: django-version
    attributes:
      label: Django version
      description: Look in your requirements.txt, or run `pip show django | grep Version`
      placeholder: e.g., 4.2.8
    validations:
      required: true

  - type: input
    id: wagtail-version
    attributes:
      label: Wagtail version
      description: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`
      placeholder: e.g., 5.2
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser version
      description: You can use https://www.whatsmybrowser.org/ to find this out
      placeholder: e.g., Chrome 120.0.6099.109
    validations:
      required: false

  - type: textarea
    id: working-on-this
    attributes:
      label: Working on this
      description: |
        Do you have thoughts on skills needed?
        Are you keen to work on this yourself once the issue has been accepted?
        Please let us know here.
      value: |
        Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you're ready to start.
    validations:
      required: false
